### ISSUE TITLE
.

### ISSUE THREAD

**Issue by 20153403349** [CloudAnarchy/Task-Scheduling#1]
Dear author, I'm sorry to disturb you. I want to quote an article related to this code. Please tell me the name or the address of the article. Your help is greatly appreciated, looking forward to your reply

**Comment by cloud-np** [comment]
Hello, not sure if I understood correctly your question
but here is the package I used to generate the workflows: 
https://docs.workflowhub.org/en/latest/

I also tried to recreate the famous algorithm HEFT and CPOP:
https://en.wikipedia.org/wiki/Heterogeneous_Earliest_Finish_Time

Hope this helps!
